BDSF(bp_diffuse_bdsf)
BDSF(bp_glossy_bdsf)
BDSF(mirror_bdsf)
BDSF(fs_conductor_bdsf)
BDSF(fs_dielectric_reflectance_bdsf)
BDSF(fs_dielectric_transmittance_bdsf)

DIRF(cos_weighted_sample_hemisphere)
DIRF(uniform_sample_hemisphere)
DIRF(sample_specular_direction)
DIRF(sample_transmit_direction)
DIRF(sample_reflect_or_transmit_direction)
