#include "Platform.h"
#include "Maths.h"
#include "Colour.h"
#include "Texture.h"
#include "bsdf.h"
#include "Scene.h"
#include "Debug.h"

#include "Platform.cpp"
#include "Maths.cpp"
#include "Colour.cpp"
#include "Texture.cpp"
#include "bsdf.cpp"
#include "Scene.cpp"
#include "Debug.cpp"
